// @ts-check

/*global module*/

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  strainsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
